// Jasmine's 50-Scholarship Junior Year Campaign
// Based on comprehensive strategy document

const SCHOLARSHIPS = [
  // ========================================
  // TIER 1: LOW-HANGING FRUIT
  // ========================================
  {
    id: 'bigfuture',
    name: 'College Board BigFuture',
    organization: 'College Board',
    amount: '$500 - $40,000',
    deadline: '2027-06-30',
    priority: 'A',
    tier: 1,
    fit: ['general'],
    difficulty: 'Low',
    essay: false,
    recommendation: false,
    transcript: false,
    notes: 'National random drawing. Do every eligible activity as soon as available. Persistence is your advantage here, not medals.',
    action: 'Log in, complete College List and Career List. Set calendar reminder for new activities.',
    url: 'https://bigfuture.collegeboard.org/pay-for-college/bigfuture-scholarships-2028',
    status: 'not_started'
  },
  {
    id: 'sallie-monthly',
    name: 'Sallie Mae $2,000 Monthly',
    organization: 'Sallie Mae',
    amount: '$2,000',
    deadline: '2027-06-30',
    priority: 'A',
    tier: 1,
    fit: ['general'],
    difficulty: 'Low',
    essay: false,
    recommendation: false,
    transcript: false,
    notes: 'National randomized drawing. 5 minutes = worthwhile. 50 minutes = wasted. Set monthly calendar reminder.',
    action: 'Complete entry. Put recurring monthly reminder on calendar.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'scholarships360',
    name: 'Scholarships360 $10,000 No-Essay',
    organization: 'Scholarships360',
    amount: '$10,000',
    deadline: '2027-06-30',
    priority: 'A',
    tier: 1,
    fit: ['general'],
    difficulty: 'Low',
    essay: false,
    recommendation: false,
    transcript: false,
    notes: 'Very broad national pool. Easy to enter ≠ easy to win. Worth entering because time cost is tiny.',
    action: 'Quick entry - spend minutes not hours.',
    url: '',
    status: 'not_started'
  },

  // ========================================
  // UNIGO SCHOLARSHIP BUNDLE (7 scholarships, 1 platform)
  // ========================================
  {
    id: 'unigo-laugh',
    name: 'Unigo Make Me Laugh',
    organization: 'Unigo',
    amount: '$1,500',
    deadline: '2026-08-31',
    priority: 'A',
    tier: 1,
    fit: ['creative'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Judges want to be entertained. Use: setup → unexpected detail → escalation → payoff. True embarrassing story beats manufactured joke.',
    action: 'Build Unigo profile once, then tackle this prompt. ~250 words.',
    url: '',
    status: 'not_started',
    essayPrompt: 'Write a funny story or joke that will make the judges laugh.',
    essayWordLimit: 250,
    essayTips: [
      'Do NOT submit a polished scholarship essay - judges want entertainment',
      'Use: setup → unexpected detail → escalation → payoff',
      'A true embarrassing story works better than a manufactured joke',
      'Consider funny photography, babysitting, baking, or family moments',
      'Specificity beats clever-sounding writing'
    ],
    essayStructure: 'Tell one specific embarrassing or funny story. Set the scene, build tension, deliver the punchline.'
  },
  {
    id: 'unigo-shout',
    name: 'Unigo Shout It Out',
    organization: 'Unigo',
    amount: '$1,500',
    deadline: '2026-09-30',
    priority: 'A',
    tier: 1,
    fit: ['creative'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Imagine having world attention. Choose ONE thing you care about. Do NOT try to solve hunger, war, climate all in 250 words.',
    action: 'Focus on one specific idea drawn from something you have actually seen.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'unigo-zombie',
    name: 'Unigo Zombie Apocalypse',
    organization: 'Unigo',
    amount: '$2,000',
    deadline: '2026-10-31',
    priority: 'A',
    tier: 1,
    fit: ['creative'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Creativity contest disguised as scholarship. Create scene judge can visualize. Use photographer instincts: setting, composition, detail, atmosphere.',
    action: 'Think visually - your photography background helps here.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'unigo-education',
    name: 'Unigo Education Matters',
    organization: 'Unigo',
    amount: '$5,000',
    deadline: '2027-03-31',
    priority: 'A',
    tier: 1,
    fit: ['academics'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Avoid generic "education gives opportunities." Answer: What has education already allowed you to do? AICE, Adobe skills, turning photography into professional work.',
    action: 'Show evidence not slogans.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'unigo-10k',
    name: 'Unigo $10K Scholarship',
    organization: 'Unigo',
    amount: '$10,000',
    deadline: '2027-03-31',
    priority: 'A',
    tier: 1,
    fit: ['general'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Higher-value short response. One surprising opening + one meaningful idea + one concrete example + memorable closing. Do NOT convert resume into prose.',
    action: 'Focus on impact, not listing achievements.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'unigo-sweet',
    name: 'Unigo Sweet and Simple',
    organization: 'Unigo',
    amount: '$1,500',
    deadline: '2027-03-31',
    priority: 'B',
    tier: 1,
    fit: ['creative'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Personal item/memory with disproportionate meaning. Camera-related could work if story reveals something beyond "I love photography."',
    action: 'Find the unexpected meaning in something small.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'unigo-abouted',
    name: 'Unigo All About Education',
    organization: 'Unigo',
    amount: '$1,500',
    deadline: '2027-03-31',
    priority: 'B',
    tier: 1,
    fit: ['academics'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Reuse education story bank but NOT same response word-for-word. Total: 7 Unigo opportunities using same platform.',
    action: 'Customize from your education story bank.',
    url: '',
    status: 'not_started'
  },

  // ========================================
  // DIGITAL RESPONSIBILITY 4-PACK ($1,000 each)
  // ========================================
  {
    id: 'dont-text-drive',
    name: "Don't Text and Drive Scholarship",
    organization: 'Digital Responsibility',
    amount: '$1,000',
    deadline: '2026-09-30',
    priority: 'A',
    tier: 1,
    fit: ['creative'],
    difficulty: 'Low',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Avoid "texting and driving is dangerous" - everyone knows that. Think like photographer: what does one second of looking away actually look like?',
    action: 'Write something personal, visual, and concrete.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'tech-addiction',
    name: 'Technology Addiction Awareness',
    organization: 'Digital Responsibility',
    amount: '$1,000',
    deadline: '2027-01-30',
    priority: 'A',
    tier: 1,
    fit: ['photography', 'creative'],
    difficulty: 'Low',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Your photography career gives interesting contradiction: tech essential for creative work, but excessive tech interferes with observing life.',
    action: 'Explore this tension - much more interesting than "phones are bad."',
    competitive_advantage: 'Your dual relationship with technology as creator and observer.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'ewaste',
    name: 'E-Waste Scholarship',
    organization: 'Digital Responsibility',
    amount: '$1,000',
    deadline: '2027-04-30',
    priority: 'B',
    tier: 1,
    fit: ['photography'],
    difficulty: 'Low',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Photography involves cameras, batteries, memory devices, computers, monitors, phones. You have a legitimate technology connection.',
    action: 'Connect your photography equipment lifecycle to e-waste issues.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'digital-privacy',
    name: 'Digital Privacy Scholarship',
    organization: 'Digital Responsibility',
    amount: '$1,000',
    deadline: '2027-06-30',
    priority: 'B',
    tier: 1,
    fit: ['photography'],
    difficulty: 'Low',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Photography introduces real privacy questions: photographing people, children, publishing online, client photos, social media, consent.',
    action: 'Share your unusually relevant perspective as a working photographer.',
    competitive_advantage: 'Real experience with photography privacy/consent issues.',
    url: '',
    status: 'not_started'
  },

  // ========================================
  // TIER 2: YOUR CREATIVE ADVANTAGE (TOP PRIORITY)
  // ========================================
  {
    id: 'vfw-voice-democracy',
    name: 'VFW Voice of Democracy',
    organization: 'VFW',
    amount: 'Up to $35,000',
    deadline: '2026-10-31',
    priority: 'A',
    tier: 2,
    fit: ['military-family', 'patriotism'],
    difficulty: 'High',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'ONE OF YOUR TOP 5 APPLICATIONS. Theme: "What a Veteran Taught Me About America." Local Post → District → State → National. 35% Originality, 35% Delivery, 30% Content.',
    action: 'Tell ONE real story. Specific memory → lesson → how it changed you → what it taught about America. Record 3-5 min audio.',
    competitive_advantage: 'If you have a personal connection to military veterans, share your authentic experience.',
    important_warning: 'AI assistance prohibited. Your essay and recording must be your own work.',
    url: 'https://www.vfw.org/VOD',
    status: 'not_started',
    essayPrompt: 'What a Veteran Taught Me About America',
    essayWordLimit: 500,
    essayFormat: 'Audio recording (3-5 minutes)',
    essayTips: [
      'This is an AUDIO essay - you will record yourself reading it',
      'Judging: 35% Originality, 35% Delivery, 30% Content',
      'Do NOT write "Veterans sacrifice for our freedom" - everyone says that',
      'Tell ONE real story from your own life with a veteran you know',
      'Structure: specific memory → lesson → how it changed you → what it taught about America',
      'You have an enormous advantage: you lived it, you do not have to imagine it',
      'Practice reading aloud - delivery matters as much as content'
    ],
    essayStructure: '1. Open with a specific scene/memory with a veteran you know\n2. What happened in that moment\n3. What it made you realize about their service\n4. The lesson you carry forward\n5. What this taught you about America specifically',
    interviewQuestions: [
      'Think of ONE specific memory with a veteran that shows what their military service meant. Describe the scene - where were you, what were you doing, what did you see or hear?',
      'In that moment, what did you realize about their service that you had not understood before?',
      'What lesson from that experience do you carry with you now? How does it affect how you act or think?',
      'When you think about what a veteran taught you, what does that say about America specifically - not just about sacrifice in general?',
      'How will you pass this lesson forward? What will you do differently because of what you learned?'
    ]
  },
  {
    id: 'youngarts',
    name: 'YoungArts National Photography',
    organization: 'YoungArts',
    amount: '$250 - $10,000',
    deadline: '2026-10-06',
    priority: 'A',
    tier: 2,
    fit: ['photography', 'arts'],
    difficulty: 'High',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'POSSIBLY YOUR BEST NATIONAL OPPORTUNITY. ~13,000 applications, 734 winners (~5.6%). Submit 10 photographs as unified series. NOT a "best pictures" contest - they want artist with point of view.',
    action: 'Build a SERIES with theme: People at Work, Growing Up, Service, Military Families, or South Florida Lives. Do NOT submit random excellent photos.',
    competitive_advantage: 'Your Scholastic Gold Medal proves your photography can survive national-level judging.',
    url: 'https://youngarts.org/apply/requirements/photography/',
    status: 'not_started'
  },
  {
    id: 'scholastic-2027',
    name: 'Scholastic Art & Writing Awards 2027',
    organization: 'Scholastic',
    amount: 'Up to $10,000',
    deadline: '2026-12-01',
    priority: 'A',
    tier: 2,
    fit: ['photography', 'arts'],
    difficulty: 'High',
    essay: false,
    recommendation: false,
    transcript: false,
    notes: 'MUST ENTER AGAIN. You already won National Gold Medal + American Visions Award. Judging is blind - your award does not give preferential treatment.',
    action: 'Do NOT try to make Warm Embrace 2. Develop work that demonstrates evolution. Two years of national recognition = dramatically more interesting.',
    competitive_advantage: 'You already proved you can win at the highest level. Show artistic evolution.',
    url: 'https://www.artandwriting.org/awards/how-to-enter/calendar/',
    status: 'not_started'
  },
  {
    id: 'jostens',
    name: 'Jostens Photo Contest',
    organization: 'Jostens',
    amount: 'Up to $1,000',
    deadline: '2027-03-31',
    priority: 'A',
    tier: 2,
    fit: ['photography'],
    difficulty: 'Moderate',
    essay: false,
    recommendation: false,
    transcript: false,
    notes: 'Opens January. You photograph ACTUAL school life - emotion, celebration, student interaction, athletics, candid moments. Different from Scholastic: Jostens values student life storytelling.',
    action: 'Do NOT send same portfolio as Scholastic. Focus on school life moments.',
    competitive_advantage: 'You are the school photographer with access to real student life moments.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'greeting-card',
    name: 'Create-A-Greeting-Card Scholarship',
    organization: 'Gallery Collection',
    amount: '$10,000',
    deadline: '2027-03-08',
    priority: 'A',
    tier: 2,
    fit: ['photography', 'arts'],
    difficulty: 'Moderate',
    essay: false,
    recommendation: false,
    transcript: false,
    notes: 'Best Scholastic photo may NOT be best greeting card photo. This needs: immediate communication, emotion, broadly relatable, works commercially.',
    action: 'Your professional photography experience may help more here than in Scholastic.',
    competitive_advantage: 'Professional experience understanding what works commercially.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'ocean-awareness',
    name: 'Ocean Awareness Contest',
    organization: 'Bow Seat',
    amount: 'Varies',
    deadline: '2027-06-30',
    priority: 'A',
    tier: 2,
    fit: ['photography', 'environmental'],
    difficulty: 'Moderate',
    essay: false,
    recommendation: false,
    transcript: false,
    notes: 'International youth contest. Theme announced September. You live in COASTAL FLORIDA. Do NOT submit pretty ocean picture. Photograph actual issues.',
    action: 'Indian River Lagoon, seagrass, coastal development, water quality, marine debris. Winning formula: Beauty + problem + human connection.',
    competitive_advantage: 'Geographic advantage - you live where ocean issues are visible.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'cspan-studentcam',
    name: 'C-SPAN StudentCam',
    organization: 'C-SPAN',
    amount: 'Varies',
    deadline: '2027-01-20',
    priority: 'A',
    tier: 2,
    fit: ['video', 'civic'],
    difficulty: 'High',
    essay: false,
    recommendation: false,
    transcript: false,
    notes: 'UNDERRATED OPPORTUNITY. Theme: "Mr. Speaker, I Rise To..." 5-6 min video. 150 prize-winning videos! Regional evaluation. Most students entering are NOT professional visual storytellers.',
    action: 'Choose problem you can actually film in Martin County and connect to Congress: water quality, veterans, housing, insurance, coastal resilience. Conduct real interviews.',
    competitive_advantage: 'You already understand composition, B-roll, visual sequencing, interviewing, editing, capturing emotion.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'al-neuharth',
    name: 'Al Neuharth Free Spirit',
    organization: 'Freedom Forum',
    amount: 'Scholarship + DC Conference',
    deadline: '2027-02-28',
    priority: 'A',
    tier: 2,
    fit: ['journalism', 'photography'],
    difficulty: 'High',
    essay: true,
    recommendation: true,
    transcript: true,
    notes: 'HIGH STRATEGIC VALUE. ~51 students selected (one per state + DC). You are competing to be FLORIDA representative. Combines nationally recognized photography + school photography + professional work + visual storytelling.',
    action: 'Strengthen photojournalism: create 2-3 documentary stories involving real people/community issues before application.',
    competitive_advantage: 'Unique combination: national recognition + professional work + school photography + entrepreneurship.',
    url: '',
    status: 'not_started'
  },

  // ========================================
  // NSHSS SCHOLARSHIP BUNDLE
  // ========================================
  {
    id: 'nshss-visual-arts',
    name: 'NSHSS Visual Arts - Photography',
    organization: 'NSHSS',
    amount: '$2,000',
    deadline: '2026-10-27',
    priority: 'A',
    tier: 2,
    fit: ['photography', 'arts'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: true,
    transcript: true,
    notes: 'BEST NSHSS FIT. 2 awards of $2,000 for photography. Reviewer sees National Gold Medal + American Visions before evaluating your photo.',
    action: 'Submit image that best represents your ARTISTIC identity, not what real-estate client would prefer. $90 membership fee (waivers available).',
    competitive_advantage: 'Third-party validation that you are a serious photographer.',
    url: 'https://www.nshss.org/scholarships/s/nshss-visual-arts-scholarship-2026/',
    status: 'not_started'
  },
  {
    id: 'nshss-film',
    name: 'NSHSS Film & Media Production',
    organization: 'NSHSS',
    amount: '$2,000',
    deadline: '2026-10-27',
    priority: 'B',
    tier: 2,
    fit: ['video'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: true,
    transcript: true,
    notes: 'Secondary to C-SPAN. The filmmaking skills from StudentCam can make this much easier.',
    action: 'If producing C-SPAN video, can leverage for this too.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'nshss-nobel',
    name: 'NSHSS Nobel Academic Excellence',
    organization: 'NSHSS',
    amount: '$5,000',
    deadline: '2026-10-01',
    priority: 'A',
    tier: 2,
    fit: ['academics'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: true,
    transcript: true,
    notes: '10 awards of $5,000. More academic than photography-specific. Do NOT pretend GPA is your only differentiator.',
    action: 'Argument: rigorous academics + national creative achievement + work + entrepreneurship + service = multidimensional academic profile.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'nshss-entrepreneur',
    name: 'NSHSS James W. Lewis Entrepreneur',
    organization: 'NSHSS',
    amount: '$5,000',
    deadline: '2026-08-25',
    priority: 'A',
    tier: 2,
    fit: ['entrepreneurship'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: true,
    transcript: true,
    notes: 'VERY HIGH if eligible. 3 awards of $5,000. Values community involvement, entrepreneurship, leadership, future impact. DEADLINE IS VERY CLOSE.',
    action: 'Discuss your photography business: How you started, working with clients, pricing, how professional differs from recreational. Do NOT rush if prerequisites not ready.',
    competitive_advantage: 'You did not join a photography club - you CREATED a business.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'nshss-goodtrouble',
    name: 'NSHSS John Lewis Good Trouble',
    organization: 'NSHSS',
    amount: '$1,000',
    deadline: '2026-10-06',
    priority: 'B',
    tier: 2,
    fit: ['activism'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: true,
    transcript: true,
    notes: '5 awards of $1,000. Rewards actual advocacy or positive disruption. FIT WARNING: Community service is NOT automatically activism.',
    action: 'Do NOT force Butterfly Gardens into "Good Trouble" narrative unless you have genuinely challenged or changed something.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'nshss-sustainability',
    name: 'NSHSS Claes Nobel Good Earth',
    organization: 'NSHSS',
    amount: '$2,000',
    deadline: '2026-09-15',
    priority: 'B',
    tier: 2,
    fit: ['environmental'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: true,
    transcript: true,
    notes: 'Use only if you can demonstrate genuine environmental interest. AICE Environmental Management course + Florida environment = foundation.',
    action: 'Actual environmental action would make this stronger.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'nshss-first',
    name: 'NSHSS Your First Scholarship',
    organization: 'NSHSS',
    amount: '$1,000',
    deadline: '2026-10-15',
    priority: 'B',
    tier: 2,
    fit: ['general'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: true,
    transcript: true,
    notes: 'Strong general-purpose. Prompt: personal strength and future. Do NOT say "hardworking."',
    action: 'Possible strength: "learning to observe" - connects to photography, children, people, professional work, how you approach the world.',
    url: '',
    status: 'not_started'
  },

  // ========================================
  // TIER 3: ESSAY AND CIVIC COMPETITIONS
  // ========================================
  {
    id: 'vfw-patriotic-art',
    name: 'VFW Young American Creative Patriotic Art',
    organization: 'VFW Auxiliary',
    amount: 'Up to $15,000',
    deadline: '2027-03-31',
    priority: 'B',
    tier: 3,
    fit: ['arts'],
    difficulty: 'Moderate',
    essay: false,
    recommendation: false,
    transcript: false,
    notes: 'Local Auxiliary → State → National. IMPORTANT: Does NOT accept photography as primary medium. Enter only if you enjoy another artistic medium.',
    action: 'Your artistic eye transfers, but do not allow this to consume time needed for photography competitions.',
    competitive_advantage: 'National Gold Medal establishes visual talent in any medium.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'fra-essay',
    name: 'Fleet Reserve Association Essay',
    organization: 'Fleet Reserve Association',
    amount: 'Up to $1,500',
    deadline: '2027-04-01',
    priority: 'A',
    tier: 3,
    fit: ['military-family'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Up to 350 words. Local branch → regional → national. Local-to-national structure makes this more attractive than dollar amount suggests.',
    action: 'Do NOT write "My parents served therefore I understand patriotism." Show what being raised around service actually CHANGED about you.',
    competitive_advantage: 'Military family background.',
    important_warning: 'AI use prohibited. Write it yourself.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'optimist-essay',
    name: 'Optimist International Essay Contest',
    organization: 'Optimist International',
    amount: '$2,500',
    deadline: '2027-02-01',
    priority: 'A',
    tier: 3,
    fit: ['arts', 'voice'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: '2026-27 Topic: "Finding My Voice in a World Full of Noise." MAY BE ONE OF YOUR BEST NON-PHOTOGRAPHY PROMPTS. Local Club → District.',
    action: 'Photography helped you learn having a voice does not mean being loudest. Photographer watches, notices, waits, listens, chooses what deserves attention. Much more original than "social media is noisy."',
    competitive_advantage: 'Your photographer perspective on finding voice through observation, not volume.',
    url: 'https://optimist.org/member/scholarships3.cfm',
    status: 'not_started',
    essayPrompt: 'Finding My Voice in a World Full of Noise',
    essayWordLimit: 800,
    essayTips: [
      'This may be YOUR BEST non-photography prompt',
      'Avoid the obvious "social media is noisy" angle - everyone will say that',
      'Your UNIQUE angle: Photography taught you that having a voice does not mean being loudest',
      'A photographer watches, notices, waits, listens, chooses what deserves attention',
      'You found your voice by learning to observe, not by being louder',
      'Show how observing through a camera lens changed how you listen to the world'
    ],
    essayStructure: '1. Describe a noisy moment (literal or figurative)\n2. How you learned to find signal in the noise through photography\n3. A specific moment behind the camera where you chose what deserved attention\n4. How this skill transfers beyond photography\n5. Your voice is different because you learned to listen first',
    interviewQuestions: [
      'Describe a time when everything felt noisy - literal noise, or too many voices/opinions/pressures. What was the situation?',
      'When did you first realize that photography was teaching you to listen differently? What was that moment like?',
      'Tell me about a specific time behind the camera when you had to choose what deserved attention. What did you notice that others might have missed?',
      'How does this way of seeing transfer to your life outside of photography? Give a specific example.',
      'What does "finding your voice" mean to you now - and how is your voice different because you learned to observe first?'
    ]
  },
  {
    id: 'optimist-oratorical',
    name: 'Optimist International Oratorical',
    organization: 'Optimist International',
    amount: '$2,500',
    deadline: '2027-02-01',
    priority: 'B',
    tier: 3,
    fit: ['service', 'leadership'],
    difficulty: 'Moderate',
    essay: false,
    recommendation: false,
    transcript: false,
    notes: 'Topic: "How My Actions Strengthen Those Around Me." Perfect for your service history.',
    action: 'Choose ONE example where someone was different because you showed up.',
    url: 'https://www.optimist.org/oratorical',
    status: 'not_started'
  },
  {
    id: 'spj-essay',
    name: 'SPJ/JEA High School Essay Contest',
    organization: 'Society of Professional Journalists',
    amount: 'Varies',
    deadline: '2027-02-28',
    priority: 'A',
    tier: 3,
    fit: ['journalism', 'photography'],
    difficulty: 'High',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'GREAT EXPECTED-VALUE OPPORTUNITY. ~145 students entered recently, 3 prizes = ~2.1% prize rate. Compare with tens of thousands at famous scholarships.',
    action: 'Read past winning essays. Study specificity, thesis, examples, economy of language. Essay can come from someone who photographs school life, works professionally, understands visual communication.',
    competitive_advantage: 'Authentic media connection + experience deciding what moments to document.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'nscda-congressional',
    name: 'NSCDA Congressional Essay',
    organization: 'National Society Colonial Dames of America',
    amount: 'Congressional Seminar + Travel',
    deadline: '2027-02-28',
    priority: 'B',
    tier: 3,
    fit: ['civic', 'history'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'State pathway → National. ~750 words. Prize is Congressional Seminar experience, not just cash. Emphasizes content, form, individuality.',
    action: 'Research completed for one civic competition can improve all: American Legion, Constituting America, Federal Bar, SAR, JFK-style competitions.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'american-legion-oratorical',
    name: 'American Legion Oratorical',
    organization: 'American Legion',
    amount: 'Up to $25,000',
    deadline: '2027-03-01',
    priority: 'B',
    tier: 3,
    fit: ['patriotism', 'constitution'],
    difficulty: 'High',
    essay: false,
    recommendation: false,
    transcript: false,
    notes: 'Must master U.S. Constitution content. 8-10 min prepared oration + 3-5 min assigned topic.',
    action: 'Start reading about Constitution NOW. Your family provides perspective on constitutional duty.',
    url: 'https://www.legion.org/get-involved/youth-programs/oratorical-contest/',
    status: 'not_started'
  },

  // ========================================
  // TIER 4: ELITE REACH + HIGH-FIT NATIONAL
  // ========================================
  {
    id: 'horatio-alger',
    name: 'Horatio Alger National Scholarship',
    organization: 'Horatio Alger Association',
    amount: 'Up to $25,000',
    deadline: '2027-03-01',
    priority: 'A',
    tier: 4,
    fit: ['perseverance', 'service', 'academics'],
    difficulty: 'High',
    essay: true,
    recommendation: true,
    transcript: true,
    notes: 'REQUIRES family AGI under $100,000. Ask parents first! 105 juniors selected nationally.',
    action: 'Confirm family income qualifies. Emphasize perseverance + what you did WHILE managing circumstances.',
    competitive_advantage: 'Your evidence: rigorous academics + working + photography business + service + national art recognition.',
    url: 'https://horatioalger.org/scholarships/',
    status: 'not_started'
  },
  {
    id: 'jfk-profile-courage',
    name: 'JFK Profile in Courage Essay',
    organization: 'Kennedy Library',
    amount: 'Up to $10,000',
    deadline: '2027-01-15',
    priority: 'B',
    tier: 4,
    fit: ['history', 'research', 'writing'],
    difficulty: 'High',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Analyze political courage of U.S. elected official since 1917. Research a FLORIDA figure for distinction.',
    action: 'Choose lesser-known Florida legislator or local official. Interview someone if possible.',
    important_warning: 'AI assistance can cause DISQUALIFICATION. Write it yourself.',
    url: 'https://www.jfklibrary.org/learn/education/profile-in-courage-essay-contest',
    status: 'not_started'
  },
  {
    id: 'coolidge',
    name: 'The Coolidge Scholarship',
    organization: 'Coolidge Foundation',
    amount: 'Full Ride (4 years)',
    deadline: '2027-01-15',
    priority: 'B',
    tier: 4,
    fit: ['academics', 'intellectual'],
    difficulty: 'Extremely High',
    essay: true,
    recommendation: true,
    transcript: true,
    notes: 'Primary criterion is academic excellence. REACH opportunity but worth applying. Apply because payoff is enormous, but never sacrifice several strong-fit applications.',
    action: 'Develop intellectual theme connecting photography to history, communication, public understanding.',
    url: 'https://coolidgescholars.org/',
    status: 'not_started'
  },
  {
    id: 'kovner',
    name: 'Kovner Opportunity Scholarship',
    organization: 'Kovner Foundation',
    amount: 'Up to $40,000',
    deadline: '2027-02-01',
    priority: 'A',
    tier: 2,
    fit: ['academics', 'service', 'leadership'],
    difficulty: 'Moderate',
    essay: true,
    recommendation: true,
    transcript: true,
    notes: 'Martin County High School is a participating school. Smaller applicant pool than national awards.',
    action: 'Tell counselor NOW that you intend to apply. Lead with academics + national art + employment + service.',
    competitive_advantage: 'Much smaller eligible population than national awards.',
    url: '',
    status: 'not_started'
  },
  {
    id: 'taco-bell-live-mas',
    name: 'Taco Bell Live Mas Scholarship',
    organization: 'Taco Bell Foundation',
    amount: 'Up to $25,000',
    deadline: '2026-10-15',
    priority: 'A',
    tier: 2,
    fit: ['entrepreneurship', 'passion'],
    difficulty: 'High',
    essay: true,
    recommendation: false,
    transcript: false,
    notes: 'Focus on passion and storytelling, not test scores. Video or written response.',
    action: 'Tell YOUR story: discovered photography → national award → your photography business → professional work.',
    competitive_advantage: 'Most students tell what they WANT to do. You show what you ALREADY did.',
    url: 'https://tacobellfoundation.org/live-mas-scholarship/',
    status: 'not_started',
    essayPrompt: 'Tell us about your passion and how you are pursuing it.',
    essayWordLimit: 500,
    essayFormat: 'Video (2 min) OR Written (500 words)',
    essayTips: [
      'Focus on PASSION and STORYTELLING, not grades or test scores',
      'Video applications often stand out more - consider recording yourself',
      'Your story arc: discovered photography → developed skill → recognition → started business → professional work',
      'Most students tell what they WANT to do. You show what you ALREADY DID.',
      'Show the progression from hobby to business to career path',
      'Include real-estate photography as proof you turned passion into income'
    ],
    essayStructure: '1. The moment photography became more than a hobby\n2. What you learned building your photography practice\n3. The validation of recognition or achievements\n4. How your passion connects to your goals\n5. Where this passion is taking you next',
    interviewQuestions: [
      'When did photography stop being just a hobby and become something more? What happened in that moment?',
      'What was it like starting your photography practice? What was the hardest part of turning your passion into something more?',
      'Tell me about a time your work was recognized. What did that mean to you?',
      'Tell me about a real paying job you did - portraits, senior photos, or real estate. What did you learn from working with actual clients?',
      'Where is this passion taking you next? What do you want to build or create in the future?'
    ]
  },
  {
    id: 'doodle-google',
    name: 'Doodle for Google',
    organization: 'Google',
    amount: '$30,000 + College Scholarship',
    deadline: '2027-03-15',
    priority: 'C',
    tier: 4,
    fit: ['arts'],
    difficulty: 'Extremely High',
    essay: false,
    recommendation: false,
    transcript: false,
    notes: 'Extremely competitive. You are photographer not primarily illustrator - should NOT displace YoungArts or Scholastic.',
    action: 'Enter only if you develop concept that genuinely excites you. Do not enter simply because it is famous.',
    url: '',
    status: 'not_started'
  }
];

// Application reuse system - 9 asset categories
const APPLICATION_ASSETS = {
  A: {
    name: 'Photography Portfolio',
    supports: ['YoungArts', 'Scholastic', 'NSHSS Visual Arts', 'Jostens', 'Ocean Awareness', 'Create-A-Greeting-Card'],
    note: '6 applications from one carefully organized photography archive'
  },
  B: {
    name: 'Military-Family Story Bank',
    supports: ['VFW Voice of Democracy', 'Fleet Reserve Association', 'American Legion', 'Military-child awards'],
    note: 'Stories about your parents service and what it taught you'
  },
  C: {
    name: 'Service Story Bank',
    supports: ['Optimist', 'Kovner', 'Horatio Alger', 'Leadership applications'],
    note: 'Ascent Church, children, Butterfly Gardens, school service, community service'
  },
  D: {
    name: 'Photography-Business Story',
    supports: ['Live Mas', 'Entrepreneurship scholarships', 'NSHSS Entrepreneur'],
    note: 'interest → skill → national recognition → your photography business → paying clients → professional RE photography'
  },
  E: {
    name: 'Academic Packet',
    supports: ['All academic scholarships'],
    note: 'Transcript, AICE courses, GPA, awards, resume, activities'
  },
  F: {
    name: 'Recommendation Packet',
    supports: ['All recommendation-requiring scholarships'],
    note: 'Resume, transcript, accomplishments, scholarship goals, deadlines, instructions for recommenders'
  },
  G: {
    name: 'Constitutional/Civics Research',
    supports: ['American Legion', 'Constituting America', 'Federal Bar', 'NSCDA', 'SAR', 'JFK'],
    note: 'Research for one can make you better at all'
  },
  H: {
    name: 'Speaking Skills',
    supports: ['Voice of Democracy', 'Optimist Oratorical', 'American Legion'],
    note: 'Preparing seriously for one improves all three'
  },
  I: {
    name: 'Financial/Merit Packet',
    supports: ['Kovner', 'Horatio Alger', 'QuestBridge', 'Need-based scholarships'],
    note: 'Comprehensive financial and merit documentation'
  }
};

// Application procedure phases
const APPLICATION_PHASES = {
  qualify: {
    title: 'Phase A: Qualify',
    checklist: [
      'Read complete eligibility requirements',
      'Confirm juniors can apply',
      'Confirm age requirements',
      'Confirm residency requirements (Florida)',
      'Confirm GPA requirements (yours: 4.0167)',
      'Confirm citizenship requirements',
      'Confirm financial need (if applicable)',
      'Confirm membership requirements',
      'Record the deadline',
      'Record the award amount',
      'Save the official application link',
      'Add to scholarship tracker'
    ]
  },
  advantage: {
    title: 'Phase B: Identify Competitive Advantage',
    prompt: 'Why might they choose me instead of another qualified student?',
    options: [
      'National award winner',
      'Regional recognition',
      'Unique skill or talent',
      'Professional experience',
      'Founder of a business',
      'Exceptional academics',
      'Leadership positions',
      'Long-term community service',
      'Works while attending school',
      'Service to others',
      'Military family connection',
      'Entrepreneurial experience',
      'First-generation college student'
    ]
  },
  plan: {
    title: 'Phase C: Make Application Plan',
    checklist: [
      'Identify what the organization values',
      'Read the scholarship mission',
      'Review previous winners if available',
      'Look for judging criteria',
      'Determine if there is an interview',
      'Identify local/regional/state/national levels',
      'Select strongest resume version',
      'Select strongest stories from essay bank',
      'Identify recommender',
      'Set internal deadline 7 DAYS EARLY'
    ]
  },
  complete: {
    title: 'Phase D: Complete Application',
    checklist: [
      'Complete personal information',
      'Use your legal name',
      'Use your registered email',
      'Upload correct scholarship resume',
      'Upload transcript',
      'Upload requested documentation',
      'Request recommendations (2 weeks early)',
      'Complete all essays',
      'Verify word counts',
      'Verify file formats',
      'Use professional file names'
    ]
  },
  essay: {
    title: 'Phase E: Write Essay',
    structure: [
      '1. Something happened (specific story)',
      '2. It affected you (thoughts/feelings)',
      '3. You did something about it (action)',
      '4. You learned something (growth)',
      '5. It affects where you are going (future)'
    ],
    avoid: [
      '"Ever since I was a little girl..."',
      '"According to the dictionary..."',
      '"I have always been passionate about..."',
      '"In today\'s fast-paced world..."'
    ]
  },
  review: {
    title: 'Phase F: Have Someone Review',
    checklist: [
      'Read essay out loud',
      'Sounds like something you would say',
      'Answers the exact prompt',
      'Remove unnecessary words',
      'Correct spelling and grammar',
      'Verify names, dates, facts',
      'Have one trusted adult review',
      'Make final decisions yourself'
    ]
  },
  submit: {
    title: 'Phase G: Final Submission',
    checklist: [
      'Correct scholarship?',
      'Correct year?',
      'Correct applicant name?',
      'Correct email?',
      'Correct phone number?',
      'Every required question answered?',
      'Correct resume?',
      'Transcript uploaded?',
      'Recommendations complete?',
      'Essay attached?',
      'Essay within word limit?',
      'Required signatures completed?',
      'Submitted before deadline?',
      'TAKE SCREENSHOT OF CONFIRMATION'
    ]
  }
};

// Export for use
if (typeof window !== 'undefined') {
  window.JASMINE_SCHOLARSHIPS = SCHOLARSHIPS;
  window.APPLICATION_PHASES = APPLICATION_PHASES;
  window.APPLICATION_ASSETS = APPLICATION_ASSETS;
}
